version: 1.0.{build}
image: Visual Studio 2019
# NuGet package config steps:
#   https://stackoverflow.com/a/42911281/1179467
#
# The following settings are stored in the global YAML configuration
#   https://ci.appveyor.com/tools/global-yaml
#
# environment:
#  nuget_user: proteomics+nuget@pnnl.gov
#  nuget_password:
#    secure: 3NGHFt0DAcM5k10SVMGsKQ==
# install:
#   nuget sources add -Name PNNLCompMassSpec -Source https://ci.appveyor.com/nuget/pnnlcompmassspec-a6xbbb3j056m -UserName %nuget_user% -Password %nuget_password%
# nuget:
#   account_feed: false
#   project_feed: false
#
before_build:
- cmd: nuget.exe restore MASIC_BuildAll.sln
build:
  project: MASIC_BuildAll.sln
  verbosity: minimal
test:
  categories:
    except:
    - DatabaseNamedUser
    - DatabaseIntegrated
artifacts:
- path: bin
  name: MASIC
- path: bin\Console\Debug
  name: MASIC_Console
- path: MASICBrowser\bin
  name: MASICBrowser
