// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "This design pattern is used to silently handle several types of non-fatal errors", Scope = "module")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parentheses are not needed", Scope = "module")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.FindSimilarParentIon(System.Double,ProgressFormNET.frmProgress)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cboSICsTypeFilter_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cboSortOrder_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkFilterByIntensity_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkFilterByMZ_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkFilterBySignalToNoise_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkFixXRange_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkFixYRange_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkShowBaselineCorrectedStats_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkShowSmoothedData_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkSortDescending_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.chkUsePeakFinder_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cmdAutoStep_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cmdJump_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cmdNext_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cmdPrevious_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cmdRedoSICPeakFindingAllData_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.cmdSelectFile_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.frmBrowser_Closing(System.Object,System.Windows.Forms.FormClosingEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.frmBrowser_Resize(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.lstParentIonData_SelectedIndexChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.mFileLoadTimer_Tick(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.mnuEditShowOptimalPeakApexCursor_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.mnuFileExit_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.mnuFileSelectMASICInputFile_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.mnuFileSelectMSMSSearchResultsFile_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.mnuHelpAbout_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.optDoNotResmooth_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.optUseButterworthSmooth_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.optUseSavitzkyGolaySmooth_CheckedChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.tmrAutoStep_Elapsed(System.Object,System.Timers.ElapsedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txStats3_KeyPress(System.Object,System.Windows.Forms.KeyPressEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtAutoStep_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtAutoStep_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtButterworthSamplingFrequency_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtButterworthSamplingFrequency_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFilterByMZ_Leave(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFilterByMZ_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFilterByMZTol_Leave(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFilterByMZTol_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFixXRange_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFixXRange_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFixYRange_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtFixYRange_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtMinimumIntensity_Leave(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtMinimumIntensity_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtMinimumSignalToNoise_Leave(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtMinimumSignalToNoise_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtPeakWidthPointsMinimum_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtPeakWidthPointsMinimum_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtSavitzkyGolayFilterOrder_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtSavitzkyGolayFilterOrder_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtStats1_KeyPress(System.Object,System.Windows.Forms.KeyPressEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.txtStats2_KeyPress(System.Object,System.Windows.Forms.KeyPressEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.InputBox.textBoxText_TextChanged(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Legacy Name", Scope = "member", Target = "~M:MASICBrowser.InputBox.textBoxText_Validating(System.Object,System.ComponentModel.CancelEventArgs)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.FindSimilarParentIon(ProgressFormNET.frmProgress)")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:MASICBrowser.frmBrowser.TestValueToString")]
